import type { Metadata } from "next";
import Link from "next/link";
import { JsonLd } from "../../components/json-ld";
import { WatchCreateRoom } from "../../components/watch-create-room";
import { WATCH_PROVIDERS } from "../../packages/watch-core";
import { alternateUrls, siteUrl } from "../../lib/site";

export const metadata: Metadata = {
  title: "Watch Together Free — Synced OTT Rooms with Video & Voice",
  description: "Create a free private watch party for Netflix, Prime Video, YouTube, JioHotstar and more with synchronized playback, chat, reactions, camera and microphone.",
  alternates: alternateUrls("/watch-together"),
  keywords: ["watch together online", "watch party free", "Netflix party alternative", "Prime Video watch party", "JioHotstar watch party", "OTT watch party India", "synchronized video with friends", "watch together with video call"],
};

const faqs = [
  ["Does Trenith stream the movie to my friends?", "No. Each participant opens the title through their own lawful OTT account. The Trenith extension synchronizes play, pause, seek and playback rate; the room carries encrypted chat and optional peer-to-peer camera or microphone media."],
  ["Is Watch Together free?", "Yes. Creating and joining a Trenith room is free and needs no Trenith account. Your OTT subscription, internet connection and any provider charges remain your responsibility."],
  ["Does it work with every OTT service?", "Launch adapters cover YouTube, Netflix, Prime Video and JioHotstar. Other listed providers use the generic HTML5 adapter in beta and may change their players without notice. Trenith publishes compatibility instead of promising unsupported native TV or mobile apps."],
  ["Are chat and room data private?", "Room messages and synchronization payloads are encrypted in the browser using a secret stored in the invitation URL fragment. Short-lived encrypted events expire automatically. Camera and microphone media uses WebRTC and is not recorded by Trenith."],
];

export default function WatchTogetherPage() {
  const structuredData = [{ "@context": "https://schema.org", "@type": "SoftwareApplication", name: "Trenith Watch Together", applicationCategory: "EntertainmentApplication", operatingSystem: "Chrome, Edge, Firefox and compatible desktop browsers", url: siteUrl("/watch-together"), offers: { "@type": "Offer", price: "0", priceCurrency: "USD" }, featureList: ["Synchronized OTT playback", "Encrypted room chat", "Live camera and microphone", "Emoji reactions", "No Trenith account"] }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }];
  return <>
    <JsonLd data={structuredData} />
    <section className="watch-hero page-frame"><div className="watch-hero-copy"><span className="watch-new-label">NEW · TRENITH LIVE</span><h1>Watch anywhere.<br /><em>Feel in the same room.</em></h1><p>Synchronize the OTT stream each friend already has, then talk face-to-face with live camera, microphone, private chat and reactions. Free. No Trenith account.</p><div className="watch-hero-points"><span><i>01</i>Own OTT account</span><span><i>02</i>Encrypted room</span><span><i>03</i>Video + voice</span></div><Link className="watch-secondary-link" href="/watch-together/supported">See verified services and setup →</Link></div><WatchCreateRoom /></section>
    <section className="watch-provider-strip"><div className="page-frame"><span>BUILT FOR</span>{WATCH_PROVIDERS.filter((item) => item.support === "launch").map((provider) => <strong key={provider.id}>{provider.name}</strong>)}<Link href="/watch-together/supported">+ more in beta</Link></div></section>
    <section className="watch-explain page-frame"><div className="section-title-row"><div><span className="section-number">01</span><h2>The stream stays with the streamer.</h2></div><p>Trenith coordinates timing and the room experience. It does not rebroadcast, download or bypass protected content.</p></div><div className="watch-flow-grid"><article><span>EXT</span><h3>Control the OTT tab</h3><p>A small browser extension observes the active HTML5 player and applies synchronized play, pause, seek and rate commands.</p></article><article><span>KEY</span><h3>Encrypt room signals</h3><p>The invitation holds an encryption secret in its URL fragment. The server stores only opaque ciphertext and temporary membership records.</p></article><article><span>P2P</span><h3>Connect camera and voice</h3><p>WebRTC carries optional live audio and video directly between room members, with TURN recovery when networks block direct paths.</p></article></div></section>
    <section className="watch-use-flow"><div className="page-frame"><div><span className="section-kicker">THREE-MINUTE SETUP</span><h2>From link to living room.</h2></div><ol><li><span>01</span><div><strong>Create the room</strong><p>Choose the streaming provider and who can control playback.</p></div></li><li><span>02</span><div><strong>Connect the OTT tab</strong><p>Install the Trenith companion and open the title you are authorized to watch.</p></div></li><li><span>03</span><div><strong>Invite friends</strong><p>Everyone opens the private link and signs in to the service with their own account.</p></div></li><li><span>04</span><div><strong>Turn on voice or camera</strong><p>Optional media controls are visible and off until each participant enables them.</p></div></li></ol></div></section>
    <section className="watch-boundaries page-frame"><div><span className="section-kicker">HONEST COMPATIBILITY</span><h2>Web browsers first. Native TV apps later.</h2><p>OTT websites change frequently. Trenith uses provider-specific adapters for launch services and a generic HTML5 fallback for others. DRM remains inside the provider player; screen capture is not used.</p><Link href="/watch-together/supported">Open compatibility matrix →</Link></div><div className="watch-boundary-stats"><article><strong>25</strong><span>sync participants</span></article><article><strong>6</strong><span>live media participants</span></article><article><strong>6h</strong><span>automatic room expiry</span></article><article><strong>0</strong><span>OTT video files handled</span></article></div></section>
    <section className="service-cta page-frame"><div><span className="section-kicker">POWERED BY TRENITH</span><h2>Need synchronized media inside your own product?</h2><p>Trenith builds secure real-time applications, WebRTC systems, browser extensions, SaaS platforms and cloud infrastructure for businesses worldwide.</p></div><a className="primary-action" href="https://www.trenith.com/contact?utm_source=trenith_tools&amp;utm_medium=product&amp;utm_campaign=watch_together" target="_blank" rel="noreferrer">Build with Trenith <span>↗</span></a></section>
    <section className="faq-section page-frame"><div><span className="section-kicker">DIRECT ANSWERS</span><h2>Watch Together FAQ</h2><p>Clear product, privacy and compatibility boundaries.</p></div><div className="faq-list">{faqs.map(([question, answer], index) => <details key={question} open={index === 0}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
  </>;
}
