import type { Metadata } from "next";
import { LegalPage } from "../../components/legal-page";
import { alternateUrls } from "../../lib/site";

export const metadata: Metadata = { title: "Open-source Software Notices", description: "Open-source components and source links used by Trenith Tools.", alternates: alternateUrls("/open-source") };

export default function OpenSourcePage() {
  return <LegalPage eyebrow="OPEN-SOURCE NOTICES" title="Built responsibly on open software." summary="Updated 20 July 2026 · Trenith owns its original product code and respects the licenses of the independent components it distributes.">
    <p className="legal-lead">Open-source components remain governed by their own licenses. Nothing on this page removes the rights their authors grant to you.</p>
    <h2>FFmpeg WebAssembly</h2><p>Audio conversion and compatibility decoding use <a href="https://github.com/ffmpegwasm/ffmpeg.wasm" target="_blank" rel="noreferrer">ffmpeg.wasm</a>. The JavaScript wrapper (<code>@ffmpeg/ffmpeg</code>) is MIT licensed. The <code>@ffmpeg/core</code> 0.12.10 WebAssembly binary that your browser downloads is <a href="https://www.gnu.org/licenses/old-licenses/gpl-2.0.html" target="_blank" rel="noreferrer">GPL-2.0-or-later</a> and is distributed unmodified. Its corresponding source and build system are published at the <a href="https://github.com/ffmpegwasm/ffmpeg.wasm/tree/main/packages/core" target="_blank" rel="noreferrer">core build package</a> and the <a href="https://github.com/ffmpegwasm/ffmpeg.wasm-core" target="_blank" rel="noreferrer">core source repository</a>, which builds on <a href="https://github.com/FFmpeg/FFmpeg" target="_blank" rel="noreferrer">upstream FFmpeg</a>.</p>
    <p><strong>Written offer.</strong> For at least three years from the date you received this binary, Trenith Technologies Pvt Ltd will supply the complete corresponding source code for the GPL-licensed <code>@ffmpeg/core</code> build we distribute, on request, for no more than our cost of physically performing distribution. Write to <a href="mailto:legal@trenith.in">legal@trenith.in</a>. FFmpeg is a trademark of its respective project and is not affiliated with Trenith.</p>
    <h2>ExifTool WebAssembly</h2><p>Metadata inspection and supported cleaning use the <code>@uswriting/exiftool</code> browser package, which is Apache-2.0 licensed. It embeds <a href="https://exiftool.org" target="_blank" rel="noreferrer">ExifTool</a> and a Perl runtime compiled to WebAssembly; ExifTool and Perl are distributed under the same terms as Perl itself — your choice of the Artistic License or GPL-1.0-or-later. Upstream license notices are preserved in the distributed package.</p>
    <h2>HEIC and TIFF image decoding</h2><p>The image editor opens Apple HEIC/HEIF and TIFF files using decoders downloaded only when such a file is opened, and decoding runs entirely in your browser. HEIC/HEIF decoding uses <a href="https://www.npmjs.com/package/heic-to" target="_blank" rel="noreferrer">heic-to</a>, which bundles <a href="https://github.com/strukturag/libheif" target="_blank" rel="noreferrer">libheif</a> and the libde265 HEVC decoder; all three are <a href="https://www.gnu.org/licenses/lgpl-3.0.html" target="_blank" rel="noreferrer">LGPL-3.0</a> and are distributed unmodified. This use is decode-only — Trenith never encodes HEVC — and their license notices are preserved in the distributed package. TIFF decoding uses <a href="https://www.npmjs.com/package/utif2" target="_blank" rel="noreferrer">utif2</a> (MIT), which depends on <a href="https://github.com/nodeca/pako" target="_blank" rel="noreferrer">pako</a> (MIT and Zlib).</p>
    <h2>Other distributed components</h2><p>Next.js, React and pdf-lib are MIT licensed. JSZip is dual licensed and used under the MIT option (MIT or GPL-3.0-or-later). GIF export uses <a href="https://www.npmjs.com/package/gifenc" target="_blank" rel="noreferrer">gifenc</a> (MIT). <code>@vercel/speed-insights</code> is Apache-2.0. <code>@vercel/analytics</code> is <a href="https://www.mozilla.org/en-US/MPL/2.0/" target="_blank" rel="noreferrer">MPL-2.0</a> and runs in the browser only after analytics consent; its source is published at <a href="https://github.com/vercel/analytics" target="_blank" rel="noreferrer">vercel/analytics</a>. Complete machine-readable dependency versions and license fields are available in the public source repository lockfile.</p>
    <h2>Source and questions</h2><p>Review the <a href="https://github.com/TrenithOfficial/trenith-tools" target="_blank" rel="noreferrer">Trenith Tools source repository</a>. Send licensing questions to legal@trenith.in.</p>
  </LegalPage>;
}
