import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "../../components/legal-page";
import { alternateUrls, COMPANY_CIN, COMPANY_NAME } from "../../lib/site";

export const metadata: Metadata = { title: "Global Privacy Notice", description: "How Trenith Tools handles files, Watch Together rooms, browser-extension signals, BYOK provider requests, analytics and privacy rights worldwide.", alternates: alternateUrls("/privacy") };

export default function PrivacyPage() {
  return <LegalPage title="Privacy that explains the real data flow." summary="Effective 18 July 2026 · Global notice with regional supplements">
    <p className="legal-lead">{COMPANY_NAME} (CIN {COMPANY_CIN}), registered in India, is the operator and data fiduciary/controller for Trenith Tools where applicable. This notice applies to tools.trenith.com and tools.trenith.in.</p>
    <h2>1. The short version</h2><p>Device-labeled tools process selected files in your browser. Trenith does not receive those file contents. Public-link tools receive the URL needed to perform the requested scan. BYOK requests send your key, prompt and selected settings to the provider you choose through the documented connection path. Non-essential analytics and marketing measurement stay off until you consent. Trenith does not sell personal data.</p>
    <h2>2. Data we process</h2>
    <div className="legal-table-wrap"><table><thead><tr><th>Data</th><th>Purpose and legal basis</th><th>Typical retention</th></tr></thead><tbody>
      <tr><td>Device tool files and metadata</td><td>Complete the operation you request. The browser processes them locally.</td><td>Current browser tab; not received by Trenith.</td></tr>
      <tr><td>Public source URL</td><td>Scan a public page or retrieve an authorized public file at your request; contract/legitimate interest.</td><td>Request duration. Security logs may remain up to 30 days.</td></tr>
      <tr><td>BYOK key, prompt, settings and provider response</td><td>Transmit the request you initiate; contract/your direction. Provider terms also apply.</td><td>Request duration on Trenith routes. Session keys remain in browser session storage; an optional encrypted vault remains until you delete it.</td></tr>
      <tr><td>Watch Together membership</td><td>Operate a room: temporary participant ID, display name, role, provider choice, opaque token hash, timestamps and encrypted event payloads; performance of the requested service/legitimate interests.</td><td>Rooms expire after 6 hours. Encrypted events expire after 10 minutes. Expired operational rows are removed during service cleanup and may remain briefly in backups.</td></tr>
      <tr><td>OTT playback activity</td><td>The companion reads the connected tab’s provider, page/title identifier and play, pause, seek, rate and timing state so participants can synchronize. This is sent only after you grant that site permission and join/connect a room.</td><td>Current extension/room session. Only encrypted short-lived room payloads reach Trenith signaling storage.</td></tr>
      <tr><td>Watch room chat, camera and microphone</td><td>Chat is encrypted in the browser. Camera/microphone media is sent to room peers with WebRTC after you turn each control on. TURN may relay encrypted transport packets when direct connection fails.</td><td>Chat ciphertext expires after 10 minutes. Trenith does not record WebRTC media. Browser/device buffers last for the call.</td></tr>
      <tr><td>Consent and privacy signals</td><td>Remember and prove your choices; legal obligation/legitimate interest.</td><td>Up to 24 months, then renewed.</td></tr>
      <tr><td>Usage, device, referrer and campaign data</td><td>Improve free tools, measure performance and understand Trenith service interest; consent where required.</td><td>Analytics properties are configured for up to 14 months where available.</td></tr>
      <tr><td>Messages and rights requests</td><td>Respond, secure accounts and meet legal duties.</td><td>As needed for the request and normally no longer than 3 years, unless law requires more.</td></tr>
    </tbody></table></div>
    <h2>3. Local processing, metadata cleaning and downloads</h2><p>A “Processed on your device” label means the source file is handled with browser APIs or locally loaded WebAssembly. Files are not intentionally uploaded to Trenith. A metadata removal result is a technical aid, not a forensic guarantee; proprietary application traces can exist outside standardized metadata fields.</p>
    <h2>3A. Watch Together and browser extension</h2><p>Each viewer opens copyrighted OTT content through their own provider account. Trenith does not receive or retransmit the movie or show. The extension requests optional access only to the streaming origin a user selects. It reads the connected player’s page/title reference and playback activity, then passes those signals to the Trenith room. Invitation secrets stay in the URL fragment and are not included in ordinary HTTP requests. Room chat and playback payloads are encrypted with that secret before storage. Display names, roles, opaque authorization hashes and connection timestamps remain server-readable so the room can operate. WebRTC protects camera and microphone media in transit between peers or through a configured TURN relay; end-to-end media behavior depends on the browsers and WebRTC topology.</p>
    <h2>4. Cookies, analytics and revenue</h2><p>Necessary storage supports security and remembers consent. Optional analytics, preference and marketing measurement require a choice through our consent panel. When enabled, aggregate product and conversion information helps Trenith maintain the free platform, improve tools and attract service clients. Trenith may also use clearly disclosed contextual sponsorship or affiliate links. We do not sell or use your file contents, private metadata, BYOK keys, prompts or outputs for advertising. See the <Link href="/cookies">Cookie Policy</Link> and <Link href="/privacy-choices">Privacy Choices</Link>.</p>
    <h2>5. Sharing and international transfers</h2><p>We use limited infrastructure, security, email and consent-gated analytics providers described on our <Link href="/sub-processors">Subprocessors page</Link>. Data may be processed outside your country using available contractual and legal safeguards. A provider you deliberately connect through BYOK processes data under its own terms and may act independently from Trenith.</p>
    <h2>6. Your regional rights</h2><p>Depending on residence and legal applicability, you may request access, correction, completion, deletion, portability, restriction, objection, withdrawal of consent, grievance handling, or review of certain automated decisions. Residents of India may exercise applicable rights under the Digital Personal Data Protection Act and phased rules. EEA and UK residents may also complain to their supervisory authority. California and other US residents may exercise applicable access, correction, deletion and opt-out rights. We honor browser Global Privacy Control as an opt-out of marketing measurement.</p>
    <h2>7. Children</h2><p>Trenith Tools is intended only for people aged 18 or older. We do not knowingly offer it to children or knowingly collect children’s personal data. Contact us if you believe a child has provided data.</p>
    <h2>8. Security and incidents</h2><p>We use access controls, encryption in transit, scoped secrets, security headers and vendor controls appropriate to the service. No system is perfectly secure. Material incidents are assessed and notified where law requires. Read our <Link href="/security">Security page</Link>.</p>
    <h2>9. Requests and grievance contact</h2><p>Email privacy requests to <a href="mailto:privacy@trenith.in">privacy@trenith.in</a>. Legal notices may be sent to <a href="mailto:legal@trenith.in">legal@trenith.in</a>. Grievances may be sent to <a href="mailto:grevience@trenith.in">grevience@trenith.in</a>. We may verify identity and authority before acting. No individual officer name is published on this page.</p>
    <h2>10. Changes</h2><p>We will update the effective date and provide additional notice or renewed consent when a material change requires it. Rights depend on the law that applies; this notice does not waive mandatory protections.</p>
  </LegalPage>;
}
