import type { Metadata } from "next";
import Link from "next/link";
import { alternateUrls } from "../../lib/site";

export const metadata: Metadata = { title: "Product Changelog", description: "Verified Trenith Tools releases, fixes and new free browser utilities.", alternates: alternateUrls("/changelog") };

const releases = [
  { date: "18 July 2026", title: "Watch Together complete beta", items: ["Added free synchronized rooms for authorized OTT web playback, with launch adapters for YouTube, Netflix, Prime Video and JioHotstar plus a generic HTML5 beta.", "Added end-to-end encrypted chat, reactions and playback/WebRTC signaling, six-hour room expiry and participant recovery.", "Added optional peer-to-peer microphone and camera for up to six media participants, with Cloudflare STUN and configurable TURN recovery.", "Added a cross-browser Manifest V3 companion with optional per-site permission, no screen capture and no remote code.", "Published provider compatibility, product boundaries, privacy disclosures, security architecture and Watch Together terms."] },
  { date: "18 July 2026", title: "Readability, real logo and all-device polish", items: ["Raised the whole type scale for comfortable reading — no text is smaller than 12px anywhere on the site.", "Restored the real Trenith shield as the browser favicon, app icon and homepage brand mark, with reliable vector icons replacing glyphs that could render as missing boxes.", "Made the feedback button genuinely deliver: it now confirms clearly and opens a prefilled email when managed delivery is not configured, so no report is ever silently dropped.", "Fixed the navigation gap where Guides and AI Studio could disappear on medium screens, and reran a full visual pass at phone, tablet and desktop widths."] },
  { date: "18 July 2026", title: "Feedback everywhere, search-intent pages and security hardening", items: ["Every page now carries a floating feedback button for problems, ideas and improvements, with honeypot bot protection and an honest direct-email fallback when managed delivery is not configured.", "Every tool page title and description was rewritten around what people actually search — free, online, private, no upload — with richer social previews.", "Production dependencies audited to zero known vulnerabilities, download filenames hardened against header injection, an oversize cap added to the audio proxy and burst rate limits added to every API route."] },
  { date: "18 July 2026", title: "Any-key AI Studio, free SEO tools and answer-engine upgrade", items: ["AI Studio now runs every workflow with whichever provider key is connected and states which provider gives the strongest result instead of blocking.", "Text to Speech speaks through built-in browser voices with no key at all; ElevenLabs remains the route for downloadable MP3 audio.", "OCR reads text from JPG, PNG and WebP scans with OpenAI, Gemini or Anthropic vision-capable keys.", "Media workflows produce complete production plans from any text model, with the source file optional in plan mode.", "New free on-device SEO tools: SERP Snippet Preview with length checks and a Keyword Density & Content Analyzer with readability and question detection.", "Every tool page now answers common questions on the page and in structured data, and the AI Studio has a clear place in the navigation."] },
  { date: "18 July 2026", title: "Deep reliability audit release", items: ["Fixed audio conversion failing to start: the private media engine worker now loads correctly on every supported browser.", "Fixed metadata removal end to end: images clean through ExifTool, PDFs through a dedicated document rewriter, MP3/FLAC/Ogg/Opus/WAV/AIFF/WebM audio through the media engine, and Word, Excel and PowerPoint documents through direct property scrubbing.", "Every cleaned file now verifies, lists its remaining structural fields and downloads individually or as one ZIP.", "Video joining, image processing and provider connections keep working when the tab is moved to the background.", "Files beyond the in-browser engine capacity now fail fast with a clear size limit instead of a generic error."] },
  { date: "17 July 2026", title: "Verified media and workflow release", items: ["Added true MP3, WAV, FLAC, Ogg, Opus and M4A/AAC audio conversion.", "Added free audio trimming and volume adjustment.", "Added FFmpeg compatibility decoding to the audio joiner and explicit output preview/download states.", "Added batch ZIP download for public audio discoveries.", "Corrected reversed PDF page ranges and the voice-conversion provider route.", "Rebuilt category discovery cards and published a capability status matrix."] },
  { date: "17 July 2026", title: "Privacy and global discovery foundation", items: ["Added local metadata inspection, cleaning and verification.", "Added global and India canonicals, hreflang, sitemap, structured data, llms.txt and consent controls.", "Added privacy, terms, cookies, choices, security, subprocessors, copyright and accessibility notices."] },
];

export default function ChangelogPage() {
  return <><section className="directory-hero page-frame compact-hero"><span className="section-kicker">WHAT CHANGED</span><h1>Shipped work.<br /><em>Plainly documented.</em></h1><p>Release notes describe user-visible changes and fixed defects. Subscribe through the <a href="/feed.xml">RSS feed</a>.</p></section><section className="changelog-list page-frame">{releases.map((release, index) => <article key={`${release.date}-${release.title}`}><div><span>{release.date}</span><b>v{releases.length - index}.0</b></div><section><h2>{release.title}</h2><ul>{release.items.map((item) => <li key={item}>{item}</li>)}</ul>{index === 0 && <Link href="/status">Review current tool status →</Link>}</section></article>)}</section></>;
}
