import type { Metadata } from "next";
import { LegalPage } from "../../components/legal-page";
import { alternateUrls, COMPANY_ADDRESS, COMPANY_CIN, COMPANY_NAME } from "../../lib/site";

export const metadata: Metadata = { title: "Terms of Use", description: "Terms for free device tools, public-link utilities, metadata removal and BYOK AI workflows from Trenith.", alternates: alternateUrls("/terms") };

export default function TermsPage() {
  return <LegalPage eyebrow="TERMS OF USE" title="Free tools. Clear responsibilities." summary="Effective 17 July 2026">
    <p className="legal-lead">These terms form an agreement between you and {COMPANY_NAME}, CIN {COMPANY_CIN}, of {COMPANY_ADDRESS}. By using Trenith Tools, you confirm that you are at least 18 and accept these terms.</p>
    <h2>1. The service</h2><p>Trenith Tools provides free browser utilities, public-source scanners and interfaces for third-party providers you connect. The service is offered without a Trenith subscription or usage price. We may support the service through Trenith business leads, contextual sponsorships, disclosed affiliate relationships and consented measurement.</p>
    <h2>2. Your content and authority</h2><p>You retain rights in your content. You must own, license or otherwise have authority to process every file, URL, voice, image, song, video, document, prompt and output you use. Do not infringe copyright, privacy, publicity, confidentiality or contract rights; bypass DRM, authentication or access controls; scrape prohibited sources; introduce malware; overload the service; or use outputs unlawfully.</p>
    <h2>3. Public-link downloader</h2><p>The downloader is for public media you are authorized to save. A page being technically accessible does not grant copying rights. Trenith may block sources, destinations, requests or patterns for security, rights protection or legal compliance.</p>
    <h2>4. Device tools and practical limits</h2><p>There is no artificial file-count quota, but browsers, codecs, memory, CPU, free disk space and file health impose real limits. Large audio jobs can require a compatible desktop browser and direct-to-disk permission. Keep original files and verify outputs before deleting anything.</p>
    <h2>5. Metadata remover</h2><p>Metadata removal targets standardized and engine-supported fields. It does not guarantee anonymity or removal of every proprietary, embedded, visible, historical or inferential trace. Review sensitive outputs in the application that created them and use specialist forensic advice when consequences are serious.</p>
    <h2>6. BYOK and third-party providers</h2><p>You authorize Trenith to transmit the requests you initiate to your selected provider. You are responsible for keys, account security, provider charges, quotas and provider terms. Providers can change models or outputs without notice. Do not connect a key you are not authorized to use. Custom endpoints must support browser CORS and are your responsibility.</p>
    <h2>7. AI outputs</h2><p>AI output may be inaccurate, incomplete, biased, similar to other output or unsuitable for your purpose. Review it with a qualified human before publishing or relying on it. The service is not professional legal, medical, financial or safety advice.</p>
    <h2>8. Trenith intellectual property</h2><p>Trenith’s brands, interface, original content and software remain protected by applicable law and licenses. Third-party components retain their own licenses and provider names remain their owners’ trademarks. Open-source notices and source links are published at <a href="/open-source">/open-source</a>. These terms do not grant rights to impersonate Trenith or resell the service as your own.</p>
    <h2>9. Availability, changes and suspension</h2><p>The free service is provided “as available,” without an uptime promise or service-level agreement. We may repair, limit, change or discontinue features and may suspend harmful or unlawful use. We will try to avoid unnecessary disruption but do not promise permanent availability.</p>
    <h2>10. Disclaimers and liability</h2><p>To the maximum extent permitted by law, Trenith disclaims implied warranties of merchantability, fitness, non-infringement and uninterrupted or error-free operation. Trenith is not liable for indirect, special, incidental, punitive or consequential loss, lost data, provider charges or lost profits. Where liability cannot be excluded, Trenith’s aggregate liability for the free service is limited to the greater of INR 1,000 or the amount you paid Trenith for the affected service in the preceding three months. Mandatory consumer rights remain unaffected.</p>
    <h2>11. Indemnity</h2><p>To the extent legally permitted, you will defend and indemnify Trenith against third-party claims arising from your unlawful content, infringement, misuse or breach of these terms. This does not apply where prohibited by consumer law or to loss caused by Trenith.</p>
    <h2>12. Governing law and disputes</h2><p>These terms are governed by Indian law. Courts in Hyderabad, Telangana have jurisdiction, subject to mandatory consumer rights and any non-waivable right to bring a claim elsewhere. Contact <a href="mailto:legal@trenith.in">legal@trenith.in</a> first so we can try to resolve the issue.</p>
    <h2>13. General</h2><p>If a provision is unenforceable, the rest remains effective. Delay is not waiver. We may assign these terms in a merger, financing or transfer of the service. Material changes will be posted with a new effective date.</p>
  </LegalPage>;
}
