import type { Metadata } from "next";
import Link from "next/link";
import { WATCH_PROVIDERS } from "../../../packages/watch-core";
import { alternateUrls } from "../../../lib/site";

export const metadata: Metadata = { title: "Supported Streaming Services — Watch Together", description: "Verified and beta browser support for Trenith Watch Together across Netflix, Prime Video, YouTube, JioHotstar and other OTT websites.", alternates: alternateUrls("/watch-together/supported") };

export default function SupportedWatchServicesPage() {
  return <><section className="directory-hero compact-hero page-frame"><span className="section-kicker">WATCH TOGETHER COMPATIBILITY</span><h1>Know what works<br />before movie night.</h1><p>Support refers to desktop OTT websites in Chromium or Firefox-compatible browsers. It does not imply affiliation with the listed services and does not cover their native mobile or TV apps.</p><div className="hero-actions"><Link className="primary-action" href="/watch-together">Create a room <span>→</span></Link><a className="text-action" href="#setup">Setup guide</a></div></section>
    <section className="watch-support-section page-frame"><div className="watch-support-legend"><span className="launch">Launch adapter</span><span className="next">Generic beta</span><span className="beta">Unverified page fallback</span></div><div className="watch-support-table"><div className="watch-support-row heading"><span>Service</span><span>Region</span><span>Playback sync</span><span>Notes</span></div>{WATCH_PROVIDERS.map((provider) => <div className="watch-support-row" key={provider.id}><strong>{provider.name}</strong><span>{provider.region}</span><span><i className={provider.support} />{provider.support === "launch" ? "Provider adapter" : provider.support === "next" ? "HTML5 beta" : "Best effort"}</span><p>{provider.id === "generic" ? "Choose the largest visible HTML5 video or audio element. Player changes and custom canvases may prevent control." : "Uses each participant’s authorized provider tab. Ads, profiles and region availability remain provider-controlled."}</p></div>)}</div></section>
    <section id="setup" className="watch-setup page-frame"><div><span className="section-kicker">BROWSER SETUP</span><h2>Install once. Grant only the service you use.</h2><p>The extension requests access to a streaming origin only after you choose Connect. Trenith does not request browsing-history permission and ships no remotely executed code.</p></div><ol><li><span>1</span><p><strong>Install the companion.</strong> Load the signed Chrome/Edge or Firefox extension when published; developers can use the verified build artifact.</p></li><li><span>2</span><p><strong>Open your OTT title.</strong> Sign in directly with the service. Trenith never sees the password.</p></li><li><span>3</span><p><strong>Connect the tab.</strong> Open the extension, approve the current provider origin and connect it to the room.</p></li><li><span>4</span><p><strong>Keep the room open.</strong> The room page handles voice, camera, chat and connection recovery.</p></li></ol></section>
    <section className="watch-support-note page-frame"><strong>Important:</strong><p>Netflix, Prime Video, JioHotstar, Disney+, YouTube and other marks belong to their respective owners. Trenith Watch Together is an independent synchronization tool and is not endorsed by them. Availability can change when a provider updates its website.</p></section></>;
}
